
```{r}
rm(list=ls(all=TRUE))
library(tidyverse)
library(nlme)
```

```{r}
shrubs <- read_csv("data/shrub_prepped.csv", show_col_types = FALSE) %>%
  mutate(CA.m2 = if_else(Author == "Battles" | Author == "Harrington", CA.m2, pi*(CW1.m/2)*(CW2.m/2)),
         lnCA = log(CA.m2),
         lnAGL = log(AGL.g),
         lnHT = log(Hgt.m))

head(shrubs)
```

```{r}
final_fits <- data.frame(
  sp_group = c("AMAL","ARPA","ARVI","CE.SP","CECO","CEIN","CEVE","CH.SP","CHSE","CO.SP","COCO","LEDA","NODE","QU.SP","RI.SP","OTHER"),
  model = c("M1","M2","M1","M1","M1","M2","M2","M1","M1","M1","M1","M1","M2","M2","M2","M1"),
  type = c("GNLS","GNLS","GNLS","NLS","NLS","GNLS","GNLS","NLS","GNLS","GNLS","GNLS","GNLS","NLS","NLS","GNLS","NLS")
)

final_fits
```

```{r}
coef_df <- data.frame(species = as.character(),
                      eqn = as.character(),
                      b1 = as.double(),
                      b2 = as.double(),
                      b3 = as.double())

coef_fn <- function(data, fits) {
  
  species <- unique(fits$sp_group)
  
  for(sp in species) {
    
    sp_data <- data %>% filter(sp_group == sp)
    sp_fit <- fits %>% filter(sp_group == sp)

    if(sp_fit$type[[1]] == "GNLS") {
      
      ctrl_gnls <- gnlsControl(maxIter = 1500, tolerance = 1e-4, minScale = 1e-10, opt = "nlminb")
      
      if(sp_fit$model[[1]] == "M1") {
        
        lm_fit1 <- lm(lnAGL ~ lnCA + lnHT, data = sp_data)
        b1start1 <- exp(lm_fit1$coef[[1]])
        b2start1 <- lm_fit1$coef[[2]]
        b3start1<- lm_fit1$coef[[3]]
        
        sp_model <- gnls(AGL.g ~ b1*(CA.m2^b2)*(Hgt.m^b3),
                         start = list(b1 = b1start1, b2 = b2start1, b3 = b3start1),
                         data = sp_data,
                         weights = varPower(),
                         control = ctrl_gnls)
        
        sp_coefs <- data.frame(species = sp_fit$sp_group[[1]],
                               eqn = sp_fit$model[[1]],
                               b1 = as.double(sp_model$coef[[1]]),
                               b2 = as.double(sp_model$coef[[2]]),
                               b3 = as.double(sp_model$coef[[3]]))
        
        coef_df <- rbind(coef_df, sp_coefs)
      
      } else if(sp_fit$model[[1]] == "M2") {
        
        lm_fit2 <- lm(lnAGL ~ lnCA, data = sp_data)
        b1start2 <- exp(lm_fit2$coef[[1]])
        b2start2 <- lm_fit2$coef[[2]]
        
        sp_data_selected <- sp_data %>% select(AGL.g, CA.m2)
        
        sp_model <- gnls(AGL.g ~ b1*(CA.m2^b2),
                         start = list(b1 = b1start2, b2 = b2start2),
                         data = sp_data_selected,
                         weights = varPower(),
                         control = ctrl_gnls)
        
        sp_coefs <- data.frame(species = sp_fit$sp_group[[1]],
                               eqn = sp_fit$model[[1]],
                               b1 = as.double(sp_model$coef[[1]]),
                               b2 = as.double(sp_model$coef[[2]]),
                               b3 = as.double(NA))
        
        coef_df <- rbind(coef_df, sp_coefs)
        
      }
  
    } else if(sp_fit$type[[1]] == "NLS") {
      
      ctrl_nls <- nls.control(maxiter = 1500, tol = 1e-4, minFactor = 1e-10)
      
      if(sp_fit$model[[1]] == "M1") {
        
        lm_fit1 <- lm(lnAGL ~ lnCA + lnHT, data = sp_data)
        b1start1 <- exp(lm_fit1$coef[[1]])
        b2start1 <- lm_fit1$coef[[2]]
        b3start1<- lm_fit1$coef[[3]]
        
        sp_model <- nls(AGL.g ~ b1*(CA.m2^b2)*(Hgt.m^b3),
                        start = list(b1 = b1start1, b2 = b2start1, b3 = b3start1),
                        data = sp_data,
                        control = ctrl_nls)
        
        sp_coefs <- data.frame(species = sp_fit$sp_group[[1]],
                               eqn = sp_fit$model[[1]],
                               b1 = as.double(summary(sp_model)$coef[1,1]),
                               b2 = as.double(summary(sp_model)$coef[2,1]),
                               b3 = as.double(summary(sp_model)$coef[3,1]))
        
        coef_df <- rbind(coef_df, sp_coefs)
      
      } else if(sp_fit$model[[1]] == "M2") {
        
        lm_fit2 <- lm(lnAGL ~ lnCA, data = sp_data)
        b1start2 <- exp(lm_fit2$coef[[1]])
        b2start2 <- lm_fit2$coef[[2]]
        
        sp_data_selected <- sp_data %>% select(AGL.g, CA.m2)
        
        sp_model <- nls(AGL.g ~ b1*(CA.m2^b2),
                        start = list(b1 = b1start2, b2 = b2start2),
                        data = sp_data,
                        control = ctrl_nls)
        
        sp_coefs <- data.frame(species = sp_fit$sp_group[[1]],
                               eqn = sp_fit$model[[1]],
                               b1 = as.double(summary(sp_model)$coef[1,1]),
                               b2 = as.double(summary(sp_model)$coef[2,1]),
                               b3 = as.double(NA))
        
        coef_df <- rbind(coef_df, sp_coefs)
        
      }
       
    }
  
  }

 return(coef_df)
  
}
```

```{r}
agl_coefs <- coef_fn(shrubs, final_fits)
```

```{r}
add <- data.frame(
  species = "NONE",
  eqn = "M3",
  b1 = as.double(NA),
  b2 = as.double(NA),
  b3 = as.double(NA)
)

agl_coefs_r <- agl_coefs %>%
  mutate(species = if_else(species == "CE.SP", "CESP", species),
         species = if_else(species == "CH.SP", "CHSP", species),
         species = if_else(species == "CO.SP", "COSP", species),
         species = if_else(species == "QU.SP", "QUSP", species),
         species = if_else(species == "RI.SP", "RISP", species)) %>%
  rbind(add)

agl_coefs_r
```

```{r}
write_csv(agl_coefs_r, "data\\agl_coefs.csv")
```
