
```{r}
rm(list=ls(all=TRUE))
suppressPackageStartupMessages(library(tidyverse))
```

```{r}
shrubs_1 <- read_csv("data/CARB_shrubs.csv", show_col_types = FALSE) %>%
  select(COMP, PLOT, TRANSECT, AZ, SPECIES, STATUS, MAJ_DIAM_m, MINOR_DIAM_m, HEIGHT_m)

plots_1 <- read_csv("data/CARB_plot_metadata.csv", show_col_types = FALSE) %>%
  select(TRANSECT, SLP_pcent, max_dist_m, comment)
  
head(shrubs_1)
head(plots_1)
```

```{r}
shrubs_2 <- full_join(shrubs_1, plots_1, by = "TRANSECT") %>%
  mutate(species = case_when(is.na(SPECIES) ~ "NONE",
                             SPECIES == "NODE" ~ "NODE",
                             SPECIES == "ARVI" ~ "ARVI",
                             SPECIES == "CEIN" ~ "CEIN",
                             SPECIES == "SYMO" ~ "OTHER",
                             SPECIES == "ROGY" ~ "OTHER",
                             SPECIES == "CHSE" ~ "CHSE",
                             SPECIES == "CHFO" ~ "OTHER",
                             SPECIES == "VAPA" ~ "OTHER",
                             SPECIES == "RIRO" ~ "RISP",
                             SPECIES == "ARPA" ~ "ARPA",
                             SPECIES == "RUPA" ~ "OTHER"),
         tran_length = max_dist_m,
         ht = if_else(HEIGHT_m == 0, 0.1, HEIGHT_m),
         crown_axis_1 = MAJ_DIAM_m,
         crown_axis_2 = MINOR_DIAM_m,
         slope = SLP_pcent,
         time = "2020") %>%
  filter(STATUS == "L" | species == "NONE") %>% # checked that this did not filter out any full transects 
  select(time, TRANSECT, tran_length, species, ht, crown_axis_1, crown_axis_2, slope) %>%
  separate(TRANSECT, c("site", "plot", "transect"))
  
shrubs_2
#write_csv(shrubs_2, "data/CARB_BFA_check.csv")
```
